name: awesome
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: genos
      POSTGRES_PASSWORD: genos
      POSTGRES_DB: awesome
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
